# Generated by Django 4.2.7 on 2023-11-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=50)),
                ('pics', models.ImageField(default='', upload_to='pics')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
