# Generated by Django 4.2.7 on 2023-11-10 12:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=50)),
                ('pics', models.ImageField(default='', upload_to='pics')),
                ('description', models.TextField(null=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Home_Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Invalid email address')])),
                ('message', models.TextField()),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('pics', models.ImageField(upload_to='product_pics')),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=100)),
                ('slug', models.SlugField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_app.category')),
            ],
        ),
    ]
