# Generated by Django 4.2.7 on 2023-11-08 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('pics', models.ImageField(upload_to='product_pics')),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=100)),
                ('slug', models.SlugField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_app.category')),
            ],
        ),
    ]
