# Generated by Django 4.2.7 on 2023-11-28 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0006_order_orderitem_order_products_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('table', models.CharField(choices=[('REGULAR TABLE', 'REGULAR TABLE'), ('FAMILY TABLE', 'FAMILY TABLE'), ('BUSINESS TABLE', 'BUSINESS TABLE')], default='REGULAR TABLE', max_length=20)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
